### PR TITLE
Return the last element of a model.

### PR DESCRIPTION
**Pull request by lcostantini**
I implemented the last method in the same way to the method first, now the two methods looks the same, have many lines repeated between them.

If you want this implementation i can find a way to made this two methods more clean and don't repeat so many lines.

### CODE REVIEW

**Comment by frodsan** [comment]
:+1: `List` has `first` and `last`. Set only `first`.

**Comment by frodsan** [comment]
If you sort with `LIMIT 0 -1` you will get all the records:

```
require "ohm"
require "cutest"

Ohm.flush

class User < Ohm::Model
  attribute :name
end

User.create(name: "alice")
User.create(name: "bob")
User.create(name: "eve")

# First implementation: (should return 1 record)
assert_equal(1, User.all.sort(limit: [0, 1]).count)

# Last implementation: (should return 1 record)
assert_equal(1, User.all.sort(limit: [0, -1]).count)
# => fails, returns 3
```

This breaks the purpose of having a last method.
Instead, you can use `SORT DESC`

```ruby
require "ohm"
require "cutest"

Ohm.flush

class User < Ohm::Model
  attribute :name
end

User.create(name: "alice")
User.create(name: "bob")
User.create(name: "eve")

records = User.all.sort(limit: [0, 1], order: "DESC")

assert_equal 1, records.count
assert_equal "eve", records.first.name
```

**Comment by soveran** [comment]
The fact that Redis doesn't allow us to pick the last element by using only offset and count means that there's no clean implementation of a `last` method for sets. Here are some ways of getting the desired behavior:

1. Use `0` as the offset and `-1` as the count to return all elements, then pick the last one with Ruby.
2. Inspect the value passed as `order`, then invert the meaning of `ASC/DESC`, and finally use `first` with the modified options instead.
3. Fetch the cardinality of the set and then use that value as the offset. As it uses an extra call to Redis, we could think about writing a Lua script. Getting the cardinality of a set is trivial for Redis, so there's no real overhead on that side.

The alternative would be to explain in the documents why there's no `last` method, and how to use `first` to get the expected result (by means of `ASC/DESC`).

The problem with 1 is the fact that fetching all the elements is not what we would expect from the `last` method, as @frodsan explained in the previous comment.

The problem with 2 is that inspecting strings and changing their contents is a lot of work for little gain (if we take into account that the behavior can be obtained by using `first` with `ASC/DESC`).

Regarding 3, we have to think if doing those operations (loading a script, etc.) are justifiable given the fact that we can get the same result with `first`. The design is not so elegant, as it will result in a completely different implementation to that of `first`.

**Comment by lcostantini** [comment]
I was trying to solve this by making the limit like this:
```ruby
User.create(name: "alice")
User.create(name: "bob")
User.create(name: "eve")

record = User.all.sort(limit: [-1, -1])

# But I still getting the 3 elements
assert_equal 3, record.count
```
Reading the [SORT](http://redis.io/commands/sort) method in Redis I figured out that the _offset_ for the **limit** method can't be a negative number and I think this is why the **sort** return all the elements.

I think I'll keep using the implementation with the _order: 'DESC'_ and _first_ method.

Thanks for the explanation and the time @frodsan @soveran.

**Comment by frodsan** [comment]
@lcostantini Cool! Thanks for reporting this :+1:

**Pull request closed without merging**
