### PR TITLE
Add explicit versions to gemspec dependencies

### PR DESCRIPTION
**Pull request by drosile**
These versions are the versions set by the `.gems` file. I can include a version bump if desired, but I prefer to leave that to the repo owners.

### CODE REVIEW

**Comment by djanowski** [comment]
Versions shouldn't be defined this explicitly as it would cause conflicts with other gems you want to install.

Did you run into issues with the definition as it was?

**Comment by drosile** [comment]
These versions are defined explicitly in the `.gems` file; I just copied them from there. I'm fine with looser specifications, of course.

There is currently an issue with msgpack v0.6.0 and ohm. Since the `msgpack` in the gemset has no version specified, this recent update to msgpack gets pulled in and breaks ohm.

**Comment by frodsan** [comment]
@drosile I ran the test suite with msgpack v0.6.0 without errors. Could you provide more information? Thanks!

**Comment by seppo0010** [comment]
@frodsan it should fail when using strings that are more than 31 bytes long and less than 256.

**Comment by soveran** [comment]
Hey @drosile, thanks a lot for this! Given the fact that it's broken with 0.6.0, we can be explicit about its version. I think msgpack is the only problematic of the bunch, because the other dependencies are under our control. What about a patch that adds an explicit version range? It would be like `"~> 0.5.0"` for now (or check [this example](https://github.com/soveran/syro/commit/86b99363fffd0364cf92dc01bd7561eb7d705e43)).

**Comment by drosile** [comment]
The version range works for me, too. I didn't know how much we should combine the issues of the gemspec not being explicit and the specific issue with the latest msgpack. I'll revise this commit to set the range, as you said. Thanks!

**Comment by soveran** [comment]
@drosile Released, thanks!

**Comment by drosile** [comment]
awesome :+1:

**Comment by frodsan** [comment]
@drosile @seppo0010 Do you know if this is fixed in recent versions of msgpack?

**Comment by drosile** [comment]
@frodsan i don't believe so, but i'm not sure about it

**Pull request merged**
